learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE URLS
app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login')
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special', views.special, name='special'),
]

learning_users/basic_app/models.py
from django.db import models

#import basic user model; it's a built-in model that we can use in user models.
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    #this way we are using built User model fields; the User built-in fields are Username, email, firstname, lastname;
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # add additional attributes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm


# imports for user authnetication login/logout

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html', context=None)

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(request.POST)
        profile_form = UserProfileInfoForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()
            # we are not saving profile info since one-to-one relationship to the extra profile attributes with the original User model
            profile = profile_form.save(commit=False)
            profile.user = user

            # Check whether there is a uploaded profile pic. 'profile_pic' is the attribute defined in models.py
            # Checking "request.FILES" is required this will have the uploaded contents like images, csv files and etc
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # the keys in the content dict are used in registration.html
    content = {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    }

    return render(request, 'basic_app/registration.html', context=content)


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        # a single line of code authenticate the login details i.e username and password. if
        user = authenticate(username=username, password=password)

        if user:    # if user is not None;
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT IS NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print("Username: {}, password: {}".format(username, password))
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request, 'basic_app/login.html', context=None)


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse('You are logged in, Nice!')

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <ul class="navbar-nav">
        <!-- Flow: When a user clicks on Register button then, based on url template basic_app:register,
        it will goto register view in views.py module and then views render corresponding html files -->
        <li class="nav-item"><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:register' %}">Register</a></li>

        {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
        {% endif %}
      </ul>
    </nav>

    <div class="container">
      {% block body_block %} -->
        <!-- Anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>
  </body>
</html>

learning_users/templates/basic_app/index.html
<!-- <!DOCTYPE html> is not required here since we are extending base.html. this extend copies all the basic boilerplate html code -->
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <div class="jumbotron">
      <h1>Django Level Five</h1>
    </div>
  {% endblock %}

learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basic_app:user_login' %}" method="POST">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username">

      <label for="password">Password:</label>
      <input type="password" name="password" value="">

      <input type="submit" name="" value="Login">
    </form>
  </div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>
        <form method="POST" enctype="multipart/form-data">
          <!-- here enctype is for storing uploaded multimedia data like images -->
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input class="btn btn-primary" type="submit" value="Register">
        </form>
      {% endif %}

    </div>
  {% endblock %}